name: Node.js CD

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: 22
          script: |
            export PATH="$HOME/n/bin:$PATH"$
            export PATH="/home/ubuntu/.local/share/pnpm:$PATH"$
            cd ~/workspace/project-chiral-backend
            pm2 startOrRestart process.json